name: C/C++ CI with Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev gcovr bc

    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp -v *.a /usr/lib || true

    - name: Compile tests with coverage
      run: |
        g++ -std=c++17 --coverage -fprofile-arcs -ftest-coverage test_fun.cpp -pthread -lgtest -lgtest_main -o tests

    - name: Run tests
      run: |
        ./tests

    - name: Generate coverage report
      run: |
        gcovr --xml cover.xml --root .
        # Извлекаем процент покрытия
        COVERAGE_PCT=$(gcovr --xml | grep -oP 'line-rate="\K[0-9.]+' | head -1)
        COVERAGE_PERCENT=$(echo "scale=0; $COVERAGE_PCT * 100 / 1" | bc)
        echo "COVERAGE=${COVERAGE_PERCENT}%" >> $GITHUB_ENV
        
        # Определяем цвет бейджа
        if [ $COVERAGE_PERCENT -ge 90 ]; then
            echo "COLOR=brightgreen" >> $GITHUB_ENV
        elif [ $COVERAGE_PERCENT -ge 70 ]; then
            echo "COLOR=green" >> $GITHUB_ENV
        elif [ $COVERAGE_PERCENT -ge 50 ]; then
            echo "COLOR=yellow" >> $GITHUB_ENV
        else
            echo "COLOR=red" >> $GITHUB_ENV
        fi
        
        echo "Coverage: ${{ env.COVERAGE }}"
        echo "Color: ${{ env.COLOR }}"

    - name: Generate coverage summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: cover.xml
        badge: true
        fail_below_min: false
        format: markdown
        output: both
        thresholds: '60 80'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: cover.xml

    - name: Create coverage badge (if GIST_SECRET is configured)
      if: env.COVERAGE != '' && secrets.GIST_SECRET != ''
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 0c003749b19fd7227ff75c6d31ad37e5
        filename: 'cover.json'
        label: 'Test Coverage'
        message: ${{ env.COVERAGE }}
        color: ${{ env.COLOR }}

    - name: Show coverage results
      run: |
        echo "=== Code Coverage Results ==="
        echo "Total Coverage: ${{ env.COVERAGE }}"
        cat code-coverage-results.md

    - name: Comment PR with coverage results
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: code-coverage-results.md
