name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools and libgtest-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
    
    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp -v *.a /usr/lib || true
    - name: Compile tests
      run: |
        g++ -std=c++17 tests.cpp -pthread -lgtest -lgtest_main -o tests
    - name: Run tests
      run: |
        ./tests
